// Autogenerated from Pigeon (v9.1.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import <Foundation/Foundation.h>

@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

@class Response;

@interface Response : NSObject
+ (instancetype)makeWithResponse:(nullable NSString *)response;
@property(nonatomic, copy, nullable) NSString * response;
@end

/// The codec used by PigeonApi.
NSObject<FlutterMessageCodec> *PigeonApiGetCodec(void);

@protocol PigeonApi
/// @return `nil` only when `error != nil`.
- (nullable Response *)testMessageFromFlutter:(NSString *)fromFlutter error:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void PigeonApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<PigeonApi> *_Nullable api);

NS_ASSUME_NONNULL_END
